# Generated by Django 5.1.4 on 2025-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
