# Generated by Django 5.1.4 on 2025-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_order_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
