# Generated by Django 5.1.4 on 2025-01-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafesettings',
            name='address',
            field=models.TextField(default='مازندران'),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='instagram_handle',
            field=models.CharField(default='mehrshad.boleyla', max_length=50),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='name',
            field=models.CharField(default='کافه بلیلا', max_length=100),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='phone_number',
            field=models.CharField(default='09965759902', max_length=15),
        ),
    ]
